name: Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  generate-docs:
    runs-on: macos-latest
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.7'
    - name: Generate Docs
      uses: fwcd/swift-docc-action@v1
      with:
        target: GoogleScholarSwift
        output: ./public
        transform-for-static-hosting: 'true'
        disable-indexing: 'true'
        hosting-base-path: GoogleScholarSwift
    - name: Check Documentation Generation
      run: |
        if [ -d "./public" ] && [ "$(ls -A ./public)" ]; then
          echo "Documentation generated successfully."
        else
          echo "Documentation generation failed."
          exit 1
        fi
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: generate-docs

    steps:
    - name: Deploy Docs
      uses: actions/deploy-pages@v1
